server:
  port: 8035
spring:
  application:
    name: Supervisor with Keycloak

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/auth/realms/myrealm"
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


#      client:
#        provider:
#          keycloak:
#            issuer-uri: "http://localhost:8080/auth/realms/myrealm"
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            provider: external
#            client-name: myrealm
#            client-id: myrealm
#            client-secret: uhgIl3fwoxTXsPxsA6rFB2HJQARk4YEc
#            scope: openid,profile
#            authorization-grant-type: authorization_code
#keycloak:
#
#  server-url: http://localhost:8080/auth
#  realm: myrealm
#  username: admin
#  password: admin

logging:
  level:
    root: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

