server:
  port: 8080
spring:
  application:
    name: Supervisor with Keycloak

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
        opaquetoken:
          client-id: ${keycloak.clientId}
          client-secret: ${keycloak.clientSecret}
          introspection-uri: ${keycloak.urls.auth}/realms/${keycloak.realm}/protocol/openid-connect/token/introspect

jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: ${keycloak.clientId}
keycloak:
  realm: appauth
  domain: localhost:9080
  clientId: app-auth-client-id
  clientSecret: RYvZsGxqpV4cwjwmLrpts6mAS34kY32r
  urls:
    auth: http://${keycloak.domain}
url-frontend-guest: http://localhost

#      client:
#        provider:
#          keycloak:
#            issuer-uri: "http://localhost:8080/auth/realms/myrealm"
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            provider: external
#            client-name: myrealm
#            client-id: myrealm
#            client-secret: uhgIl3fwoxTXsPxsA6rFB2HJQARk4YEc
#            scope: openid,profile
#            authorization-grant-type: authorization_code
#keycloak:
#
#  server-url: http://localhost:8080/auth
#  realm: myrealm
#  username: admin
#  password: admin

logging:
  level:
    root: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

